from types import SimpleNamespace

from app.services.cmd_generator import CommandGenerator


def make_asset(bien_id, bien_designation):
    return SimpleNamespace(
        bien_id=bien_id,
        bien_designation=bien_designation
    )


def test_sanitize_value_none_returns_empty_string():

    generator = CommandGenerator()

    assert generator.sanitize_value(None) == ""


def test_sanitize_value_strips_and_replaces_special_characters():

    generator = CommandGenerator()

    value = "  PC \r\n Portable | Neuf  "

    assert generator.sanitize_value(value) == "PC    Portable - Neuf"


def test_sanitize_value_converts_non_string_to_string():

    generator = CommandGenerator()

    assert generator.sanitize_value(1001) == "1001"


def test_generate_writes_header_and_print_lines(tmp_path):

    generator = CommandGenerator(output_dir=tmp_path)

    assets = [
        make_asset("1001", "PC Portable"),
        make_asset("1002", "Ecran"),
    ]

    filename = generator.generate(job_id=42, assets=assets)

    assert filename == "print_job_42.cmd"

    content = (tmp_path / filename).read_text(encoding="utf-8")

    lines = content.split("\n")

    assert lines[0] == "REM RFID PRINT JOB 42"
    assert lines[1] == "REM Generated by RFID PRINTING"
    assert lines[2] == ""
    assert "PRINT|bien_id=1001|designation=PC Portable" in lines
    assert "PRINT|bien_id=1002|designation=Ecran" in lines


def test_generate_sanitizes_pipe_and_newlines_in_asset_fields(tmp_path):

    generator = CommandGenerator(output_dir=tmp_path)

    assets = [make_asset("1001", "PC | Portable\nNeuf")]

    filename = generator.generate(job_id=1, assets=assets)

    content = (tmp_path / filename).read_text(encoding="utf-8")

    assert "PRINT|bien_id=1001|designation=PC - Portable Neuf" in content
    # Un pipe non échappé dans une valeur casserait le format bien_id=...|designation=...
    assert content.count("|") == 2


def test_generate_with_no_assets_writes_only_header(tmp_path):

    generator = CommandGenerator(output_dir=tmp_path)

    filename = generator.generate(job_id=7, assets=[])

    content = (tmp_path / filename).read_text(encoding="utf-8")

    assert "PRINT|" not in content
    assert "REM RFID PRINT JOB 7" in content


def test_generate_creates_output_dir_if_missing(tmp_path):

    output_dir = tmp_path / "nested" / "generated"

    assert not output_dir.exists()

    generator = CommandGenerator(output_dir=output_dir)

    assert output_dir.exists()

    filename = generator.generate(job_id=1, assets=[])

    assert (output_dir / filename).exists()


def test_generate_overwrites_existing_file(tmp_path):

    generator = CommandGenerator(output_dir=tmp_path)

    generator.generate(job_id=1, assets=[make_asset("1001", "PC")])
    generator.generate(job_id=1, assets=[make_asset("2002", "Ecran")])

    content = (tmp_path / "print_job_1.cmd").read_text(encoding="utf-8")

    assert "1001" not in content
    assert "2002" in content
