from types import SimpleNamespace

import pytest

from app.services.cmd_generator import CommandGenerator, DuplicateFilenameError


def make_asset(bien_id, bien_designation):
    return SimpleNamespace(
        bien_id=bien_id,
        bien_designation=bien_designation
    )


def test_sanitize_value_none_returns_empty_string():

    generator = CommandGenerator()

    assert generator.sanitize_value(None) == ""


def test_sanitize_value_strips_and_replaces_special_characters():

    generator = CommandGenerator()

    value = "  PC \r\n Portable | Neuf  "

    assert generator.sanitize_value(value) == "PC    Portable - Neuf"


def test_sanitize_value_converts_non_string_to_string():

    generator = CommandGenerator()

    assert generator.sanitize_value(1001) == "1001"


def test_sanitize_filename_replaces_invalid_characters():

    generator = CommandGenerator()

    assert generator.sanitize_filename("2026/0001") == "2026_0001"
    assert generator.sanitize_filename('a"b<c>d') == "a_b_c_d"


def test_sanitize_filename_empty_value_falls_back_to_default():

    generator = CommandGenerator()

    assert generator.sanitize_filename("") == "bien"
    assert generator.sanitize_filename(None) == "bien"


def test_render_filename_template_combines_job_and_asset_placeholders():

    generator = CommandGenerator()

    asset = make_asset("1001", "PC Portable")

    assert (
        generator.render_filename_template(
            "LOT{{JobId}}_{{BienId}}", 42, asset
        )
        == "LOT42_1001"
    )


def test_render_filename_template_leaves_unknown_placeholder_untouched():

    generator = CommandGenerator()

    asset = make_asset("1001", "PC Portable")

    assert (
        generator.render_filename_template(
            "{{ChampInexistant}}_{{BienId}}", 42, asset
        )
        == "{{ChampInexistant}}_1001"
    )


def test_render_filename_template_sanitizes_invalid_filename_characters():

    generator = CommandGenerator()

    asset = make_asset("2026/0001", "PC Portable")

    assert (
        generator.render_filename_template("{{BienId}}", 42, asset)
        == "2026_0001"
    )


def test_generate_writes_one_file_per_asset_directly_in_output_dir(
    tmp_path
):

    generator = CommandGenerator(output_dir=tmp_path)

    assets = [
        make_asset("1001", "PC Portable"),
        make_asset("1002", "Ecran"),
    ]

    filenames = generator.generate(job_id=42, assets=assets)

    assert filenames == ["print_job_42_1001.cmd", "print_job_42_1002.cmd"]

    assert sorted(f.name for f in tmp_path.glob("*.cmd")) == filenames

    content_1001 = (
        tmp_path / "print_job_42_1001.cmd"
    ).read_text(encoding="utf-8")
    lines_1001 = content_1001.split("\n")

    assert lines_1001[0] == "REM RFID PRINT JOB 42"
    assert lines_1001[1] == "REM Generated by RFID PRINTING"
    assert lines_1001[2] == ""
    assert "PRINT|bien_id=1001|designation=PC Portable" in content_1001
    assert "1002" not in content_1001

    content_1002 = (
        tmp_path / "print_job_42_1002.cmd"
    ).read_text(encoding="utf-8")

    assert "PRINT|bien_id=1002|designation=Ecran" in content_1002
    assert "1001" not in content_1002


def test_generate_sanitizes_pipe_and_newlines_in_asset_fields(tmp_path):

    generator = CommandGenerator(output_dir=tmp_path)

    assets = [make_asset("1001", "PC | Portable\nNeuf")]

    filenames = generator.generate(job_id=1, assets=assets)

    content = (tmp_path / filenames[0]).read_text(encoding="utf-8")

    assert "PRINT|bien_id=1001|designation=PC - Portable Neuf" in content
    # Un pipe non échappé dans une valeur casserait le format bien_id=...|designation=...
    assert content.count("|") == 2


def test_generate_with_no_assets_creates_no_cmd_file(tmp_path):

    generator = CommandGenerator(output_dir=tmp_path)

    filenames = generator.generate(job_id=7, assets=[])

    assert filenames == []
    assert list(tmp_path.glob("*.cmd")) == []


def test_generate_creates_output_dir_if_missing(tmp_path):

    output_dir = tmp_path / "nested" / "generated"

    assert not output_dir.exists()

    generator = CommandGenerator(output_dir=output_dir)

    assert output_dir.exists()

    filenames = generator.generate(
        job_id=1, assets=[make_asset("1001", "PC")]
    )

    assert (output_dir / filenames[0]).exists()


def test_generate_uses_custom_filename_template(tmp_path):

    generator = CommandGenerator(output_dir=tmp_path)

    filenames = generator.generate(
        job_id=42,
        assets=[make_asset("1001", "PC")],
        filename_template="ETIQ_{{BienId}}"
    )

    assert filenames == ["ETIQ_1001.cmd"]
    assert (tmp_path / "ETIQ_1001.cmd").exists()


def test_generate_raises_on_duplicate_filenames_and_writes_nothing(
    tmp_path
):
    """
    Un gabarit de nom de fichier qui ne varie pas par bien (ex. sans
    {{BienId}}) écraserait silencieusement les fichiers précédents du
    même lot : la génération est refusée entièrement plutôt que
    d'écrire partiellement les fichiers.
    """

    generator = CommandGenerator(output_dir=tmp_path)

    assets = [make_asset("1001", "PC"), make_asset("1002", "Ecran")]

    with pytest.raises(DuplicateFilenameError):
        generator.generate(
            job_id=1,
            assets=assets,
            filename_template="LOT_FIXE"
        )

    assert list(tmp_path.glob("*.cmd")) == []
