from types import SimpleNamespace

from app.services.cmd_generator import CommandGenerator


def make_asset(bien_id, bien_designation):
    return SimpleNamespace(
        bien_id=bien_id,
        bien_designation=bien_designation
    )


def test_sanitize_value_none_returns_empty_string():

    generator = CommandGenerator()

    assert generator.sanitize_value(None) == ""


def test_sanitize_value_strips_and_replaces_special_characters():

    generator = CommandGenerator()

    value = "  PC \r\n Portable | Neuf  "

    assert generator.sanitize_value(value) == "PC    Portable - Neuf"


def test_sanitize_value_converts_non_string_to_string():

    generator = CommandGenerator()

    assert generator.sanitize_value(1001) == "1001"


def test_sanitize_filename_replaces_invalid_characters():

    generator = CommandGenerator()

    assert generator.sanitize_filename("2026/0001") == "2026_0001"
    assert generator.sanitize_filename('a"b<c>d') == "a_b_c_d"


def test_sanitize_filename_empty_value_falls_back_to_default():

    generator = CommandGenerator()

    assert generator.sanitize_filename("") == "bien"
    assert generator.sanitize_filename(None) == "bien"


def test_generate_writes_one_file_per_asset_directly_in_output_dir(
    tmp_path
):

    generator = CommandGenerator(output_dir=tmp_path)

    assets = [
        make_asset("1001", "PC Portable"),
        make_asset("1002", "Ecran"),
    ]

    prefix = generator.generate(job_id=42, assets=assets)

    assert prefix == "print_job_42"

    assert sorted(f.name for f in tmp_path.glob("*.cmd")) == [
        "print_job_42_1001.cmd", "print_job_42_1002.cmd"
    ]

    content_1001 = (
        tmp_path / "print_job_42_1001.cmd"
    ).read_text(encoding="utf-8")
    lines_1001 = content_1001.split("\n")

    assert lines_1001[0] == "REM RFID PRINT JOB 42"
    assert lines_1001[1] == "REM Generated by RFID PRINTING"
    assert lines_1001[2] == ""
    assert "PRINT|bien_id=1001|designation=PC Portable" in content_1001
    assert "1002" not in content_1001

    content_1002 = (
        tmp_path / "print_job_42_1002.cmd"
    ).read_text(encoding="utf-8")

    assert "PRINT|bien_id=1002|designation=Ecran" in content_1002
    assert "1001" not in content_1002


def test_generate_sanitizes_pipe_and_newlines_in_asset_fields(tmp_path):

    generator = CommandGenerator(output_dir=tmp_path)

    assets = [make_asset("1001", "PC | Portable\nNeuf")]

    prefix = generator.generate(job_id=1, assets=assets)

    content = (tmp_path / f"{prefix}_1001.cmd").read_text(
        encoding="utf-8"
    )

    assert "PRINT|bien_id=1001|designation=PC - Portable Neuf" in content
    # Un pipe non échappé dans une valeur casserait le format bien_id=...|designation=...
    assert content.count("|") == 2


def test_generate_with_no_assets_creates_no_cmd_file(tmp_path):

    generator = CommandGenerator(output_dir=tmp_path)

    prefix = generator.generate(job_id=7, assets=[])

    assert list(tmp_path.glob(f"{prefix}_*.cmd")) == []


def test_generate_creates_output_dir_if_missing(tmp_path):

    output_dir = tmp_path / "nested" / "generated"

    assert not output_dir.exists()

    generator = CommandGenerator(output_dir=output_dir)

    assert output_dir.exists()

    prefix = generator.generate(job_id=1, assets=[make_asset("1001", "PC")])

    assert (output_dir / f"{prefix}_1001.cmd").exists()


def test_generate_removes_stale_files_from_previous_generation(tmp_path):

    generator = CommandGenerator(output_dir=tmp_path)

    generator.generate(job_id=1, assets=[make_asset("1001", "PC")])
    prefix = generator.generate(
        job_id=1, assets=[make_asset("2002", "Ecran")]
    )

    assert sorted(f.name for f in tmp_path.glob(f"{prefix}_*.cmd")) == [
        "print_job_1_2002.cmd"
    ]


def test_list_generated_files_returns_sorted_cmd_filenames(tmp_path):

    generator = CommandGenerator(output_dir=tmp_path)

    generator.generate(
        job_id=1,
        assets=[make_asset("2002", "Ecran"), make_asset("1001", "PC")]
    )

    assert generator.list_generated_files("print_job_1") == [
        "print_job_1_1001.cmd", "print_job_1_2002.cmd"
    ]


def test_list_generated_files_returns_empty_list_when_no_match(tmp_path):

    generator = CommandGenerator(output_dir=tmp_path)

    assert generator.list_generated_files("print_job_999") == []
