import re
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent.parent

PLACEHOLDER_PATTERN = re.compile(r"\{\{(\w+)\}\}")

# Placeholders disponibles dans le gabarit de ligne (un par bien imprimé).
ASSET_PLACEHOLDERS = {
    "BienId": lambda asset: asset.bien_id,
    "Designation": lambda asset: asset.bien_designation,
    "DateSortie": lambda asset: asset.bien_amort_date_sortie,
    "Statut": lambda asset: "Actif" if asset.is_active else "Exclu",
    "NumeroLocal": lambda asset: asset.local_numero,
    "Immeuble": lambda asset: asset.immeuble_libelle,
    "Niveau": lambda asset: asset.niveau_libelle,
    "Local": lambda asset: asset.local_libelle,
}

# Placeholders disponibles dans le gabarit d'en-tête (une fois par lot).
JOB_PLACEHOLDERS = {
    "JobId": lambda job_id: job_id,
}

DEFAULT_HEADER_TEMPLATE = (
    "REM RFID PRINT JOB {{JobId}}\n"
    "REM Generated by RFID PRINTING\n"
    "\n"
)

DEFAULT_LINE_TEMPLATE = (
    "PRINT|bien_id={{BienId}}|designation={{Designation}}"
)


class CommandGenerator:

    def __init__(
        self,
        output_dir=None
    ):

        self.output_dir = (
            Path(output_dir)
            if output_dir
            else BASE_DIR / "generated"
        )

        self.output_dir.mkdir(
            parents=True,
            exist_ok=True
        )

    def sanitize_value(
        self,
        value
    ) -> str:

        if value is None:
            return ""

        return (
            str(value)
            .replace("\r", " ")
            .replace("\n", " ")
            .replace("|", "-")
            .strip()
        )

    def render_template(
        self,
        template: str,
        placeholder_map: dict,
        context
    ) -> str:
        """
        Remplace chaque {{Placeholder}} du gabarit par la valeur
        correspondante (sanitisée). Un placeholder inconnu est laissé
        tel quel dans le résultat, pour rester visible plutôt que de
        disparaître silencieusement (aide à repérer une faute de frappe
        dans le gabarit).
        """

        def replace(match: re.Match) -> str:

            name = match.group(1)

            if name not in placeholder_map:
                return match.group(0)

            return self.sanitize_value(
                placeholder_map[name](context)
            )

        return PLACEHOLDER_PATTERN.sub(replace, template)

    def sanitize_filename(
        self,
        value
    ) -> str:
        """
        Comme sanitize_value, en interdisant en plus les caractères
        invalides dans un nom de fichier (le Bien ID sert de nom de
        fichier, un caractère comme "/" casserait sinon le chemin).
        """

        text = re.sub(
            r'[\\/:*?"<>|]',
            "_",
            self.sanitize_value(value)
        )

        return text or "bien"

    def generate(
        self,
        job_id: int,
        assets: list,
        header_template: str = None,
        line_template: str = None
    ) -> str:
        """
        Génère un fichier .cmd par bien du lot (et non plus un fichier
        unique pour tout le lot), déposés dans un sous-dossier dédié à
        ce lot. Retourne le nom de ce sous-dossier (relatif à
        output_dir). Une génération précédente du même lot est
        remplacée intégralement (le dossier ne conserve jamais que les
        fichiers de la dernière génération).
        """

        header_template = header_template or DEFAULT_HEADER_TEMPLATE
        line_template = line_template or DEFAULT_LINE_TEMPLATE

        folder_name = f"print_job_{job_id}"

        job_dir = self.output_dir / folder_name

        job_dir.mkdir(
            parents=True,
            exist_ok=True
        )

        for existing_file in job_dir.glob("*.cmd"):
            existing_file.unlink()

        header = self.render_template(
            header_template,
            JOB_PLACEHOLDERS,
            job_id
        )

        for asset in assets:

            line = self.render_template(
                line_template,
                ASSET_PLACEHOLDERS,
                asset
            )

            asset_filename = (
                f"{self.sanitize_filename(asset.bien_id)}.cmd"
            )

            (job_dir / asset_filename).write_text(
                header + line,
                encoding="utf-8"
            )

        return folder_name

    def list_generated_files(self, folder_name: str) -> list:
        """
        Liste les fichiers .cmd déposés dans le sous-dossier d'un lot
        déjà généré (triés par nom), pour affichage sur la page du lot.
        """

        job_dir = self.output_dir / folder_name

        if not job_dir.is_dir():
            return []

        return sorted(
            generated_file.name
            for generated_file in job_dir.glob("*.cmd")
        )
