import re
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent.parent

PLACEHOLDER_PATTERN = re.compile(r"\{\{(\w+)\}\}")

# Placeholders disponibles dans le gabarit de ligne (un par bien imprimé).
ASSET_PLACEHOLDERS = {
    "BienId": lambda asset: asset.bien_id,
    "Designation": lambda asset: asset.bien_designation,
    "DateSortie": lambda asset: asset.bien_amort_date_sortie,
    "Statut": lambda asset: "Actif" if asset.is_active else "Exclu",
    "NumeroLocal": lambda asset: asset.local_numero,
    "Immeuble": lambda asset: asset.immeuble_libelle,
    "Niveau": lambda asset: asset.niveau_libelle,
    "Local": lambda asset: asset.local_libelle,
}

# Placeholders disponibles dans le gabarit d'en-tête (une fois par lot).
JOB_PLACEHOLDERS = {
    "JobId": lambda job_id: job_id,
}

DEFAULT_HEADER_TEMPLATE = (
    "REM RFID PRINT JOB {{JobId}}\n"
    "REM Generated by RFID PRINTING\n"
    "\n"
)

DEFAULT_LINE_TEMPLATE = (
    "PRINT|bien_id={{BienId}}|designation={{Designation}}"
)


class CommandGenerator:

    def __init__(
        self,
        output_dir=None
    ):

        self.output_dir = (
            Path(output_dir)
            if output_dir
            else BASE_DIR / "generated"
        )

        self.output_dir.mkdir(
            parents=True,
            exist_ok=True
        )

    def sanitize_value(
        self,
        value
    ) -> str:

        if value is None:
            return ""

        return (
            str(value)
            .replace("\r", " ")
            .replace("\n", " ")
            .replace("|", "-")
            .strip()
        )

    def render_template(
        self,
        template: str,
        placeholder_map: dict,
        context
    ) -> str:
        """
        Remplace chaque {{Placeholder}} du gabarit par la valeur
        correspondante (sanitisée). Un placeholder inconnu est laissé
        tel quel dans le résultat, pour rester visible plutôt que de
        disparaître silencieusement (aide à repérer une faute de frappe
        dans le gabarit).
        """

        def replace(match: re.Match) -> str:

            name = match.group(1)

            if name not in placeholder_map:
                return match.group(0)

            return self.sanitize_value(
                placeholder_map[name](context)
            )

        return PLACEHOLDER_PATTERN.sub(replace, template)

    def generate(
        self,
        job_id: int,
        assets: list,
        header_template: str = None,
        line_template: str = None
    ) -> str:

        header_template = header_template or DEFAULT_HEADER_TEMPLATE
        line_template = line_template or DEFAULT_LINE_TEMPLATE

        filename = f"print_job_{job_id}.cmd"

        file_path = (
            self.output_dir / filename
        )

        header = self.render_template(
            header_template,
            JOB_PLACEHOLDERS,
            job_id
        )

        lines = [
            self.render_template(
                line_template,
                ASSET_PLACEHOLDERS,
                asset
            )
            for asset in assets
        ]

        content = header + "\n".join(lines)

        file_path.write_text(
            content,
            encoding="utf-8"
        )

        return filename
