"""add_rfid_scan_tables

Revision ID: 2a75c9448f34
Revises: 70a01684bcbf
Create Date: 2026-08-13 14:15:13.740717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a75c9448f34'
down_revision: Union[str, Sequence[str], None] = '70a01684bcbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfid_scan_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_by', sa.String(length=100), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfid_scan_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_file_id', sa.Integer(), nullable=False),
    sa.Column('lieu_numero', sa.String(length=50), nullable=False),
    sa.Column('bien_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['scan_file_id'], ['rfid_scan_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfid_scan_lines')
    op.drop_table('rfid_scan_files')
    # ### end Alembic commands ###
