"""add_glpi_lieu_statut_columns

Revision ID: 3736f6fe47a2
Revises: 985cea736cfa
Create Date: 2026-08-18 08:44:42.794311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3736f6fe47a2'
down_revision: Union[str, Sequence[str], None] = '985cea736cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glpi_assets', sa.Column('lieu', sa.String(length=255), nullable=True))
    op.add_column('glpi_assets', sa.Column('statut', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('glpi_assets', 'statut')
    op.drop_column('glpi_assets', 'lieu')
    # ### end Alembic commands ###
