"""add_asset_utilisateur_column

Revision ID: 6c7b0d0920f5
Revises: b80ca97d88f8
Create Date: 2026-08-21 13:28:54.105966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c7b0d0920f5'
down_revision: Union[str, Sequence[str], None] = 'b80ca97d88f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('utilisateur', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'utilisateur')
    # ### end Alembic commands ###
