"""add_cmd_templates_table

Revision ID: 70a01684bcbf
Revises: d2087f81846f
Create Date: 2026-08-12 14:24:16.806203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70a01684bcbf'
down_revision: Union[str, Sequence[str], None] = 'd2087f81846f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cmd_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_template', sa.Text(), nullable=False),
    sa.Column('line_template', sa.Text(), nullable=False),
    sa.Column('updated_by', sa.String(length=100), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cmd_templates')
    # ### end Alembic commands ###
