"""add_destination_and_bureau_tables

Revision ID: 8c04d96e73f7
Revises: 3736f6fe47a2
Create Date: 2026-08-19 11:37:15.845831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c04d96e73f7'
down_revision: Union[str, Sequence[str], None] = '3736f6fe47a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bureau_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_by', sa.String(length=100), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('added_count', sa.Integer(), nullable=True),
    sa.Column('updated_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('libelle', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle')
    )
    op.create_table('bureau_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codelieu', sa.String(length=100), nullable=False),
    sa.Column('batiment', sa.String(length=255), nullable=True),
    sa.Column('etage', sa.String(length=255), nullable=True),
    sa.Column('bureau', sa.String(length=255), nullable=True),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['bureau_imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codelieu')
    )
    op.add_column('assets', sa.Column('destination', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'destination')
    op.drop_table('bureau_mappings')
    op.drop_table('destinations')
    op.drop_table('bureau_imports')
    # ### end Alembic commands ###
