"""add_glpi_tables

Revision ID: 985cea736cfa
Revises: 66fbd384bd90
Create Date: 2026-08-17 12:28:29.372435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '985cea736cfa'
down_revision: Union[str, Sequence[str], None] = '66fbd384bd90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glpi_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('glpi_type', sa.String(length=50), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_by', sa.String(length=100), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('added_count', sa.Integer(), nullable=True),
    sa.Column('updated_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('glpi_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bien_id', sa.String(length=100), nullable=False),
    sa.Column('numero_piece', sa.String(length=100), nullable=True),
    sa.Column('glpi_type', sa.String(length=50), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['glpi_imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bien_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('glpi_assets')
    op.drop_table('glpi_imports')
    # ### end Alembic commands ###
