"""add_glpi_asset_utilisateur_column

Revision ID: b0d938430677
Revises: 749d6f4769ed
Create Date: 2026-08-20 13:47:13.279209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0d938430677'
down_revision: Union[str, Sequence[str], None] = '749d6f4769ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glpi_assets', sa.Column('utilisateur', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('glpi_assets', 'utilisateur')
    # ### end Alembic commands ###
