"""add_glpi_asset_numero_serie_column

Revision ID: b80ca97d88f8
Revises: b0d938430677
Create Date: 2026-08-21 12:37:26.375180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b80ca97d88f8'
down_revision: Union[str, Sequence[str], None] = 'b0d938430677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('glpi_assets', sa.Column('numero_serie', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('glpi_assets', 'numero_serie')
    # ### end Alembic commands ###
