"""add_asset_location_columns

Revision ID: d2087f81846f
Revises: 79ef5bea98e2
Create Date: 2026-08-12 13:48:52.512182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2087f81846f'
down_revision: Union[str, Sequence[str], None] = '79ef5bea98e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('local_numero', sa.String(length=100), nullable=True))
    op.add_column('assets', sa.Column('immeuble_libelle', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('niveau_libelle', sa.String(length=255), nullable=True))
    op.add_column('assets', sa.Column('local_libelle', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'local_libelle')
    op.drop_column('assets', 'niveau_libelle')
    op.drop_column('assets', 'immeuble_libelle')
    op.drop_column('assets', 'local_numero')
    # ### end Alembic commands ###
