"""add_destination_bureau_imports_table

Revision ID: ebfdcd8bed6d
Revises: fce9fbbbfa99
Create Date: 2026-09-09 14:26:11.016105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfdcd8bed6d'
down_revision: Union[str, Sequence[str], None] = 'fce9fbbbfa99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_bureau_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('imported_by', sa.String(length=100), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('updated_count', sa.Integer(), nullable=True),
    sa.Column('unmatched_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('destination_bureau_imports')
    # ### end Alembic commands ###
